The_Hacking_Project/S4_Initiation_Rails/J2_first_steps/a_pages_statiques/je_me_presente/config/routes.rb
Rails.application.routes.draw do
  get '/contact', to: 'static_pages#contact'	#,	as: 'contact'	

  get '/about/(:var)', to: 'static_pages#about', as: 'apropos'

  root 'static_pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

The_Hacking_Project/S4_Initiation_Rails/J2_first_steps/a_pages_statiques/je_me_presente/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
	@nom_page=params[:var]
  end
end

The_Hacking_Project/S4_Initiation_Rails/J2_first_steps/a_pages_statiques/je_me_presente/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

The_Hacking_Project/S4_Initiation_Rails/J2_first_steps/a_pages_statiques/je_me_presente/app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

<% if @nom_page %>
   <p>Nous sommes dans la page de <%= @nom_page %></p>
<% end %>

<%= link_to 'ma super page', apropos_path(var: "moi") %>
<%= link_to 'ta super page', apropos_path(var: "toi") %> 
<%= link_to 'default page', apropos_path %>

The_Hacking_Project/S4_Initiation_Rails/J2_first_steps/a_pages_statiques/je_me_presente/app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

The_Hacking_Project/S4_Initiation_Rails/J2_first_steps/a_pages_statiques/je_me_presente/app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>bienvenue sur mon site lol mdr 😇❤️😻" pour home</p>