The_Hacking_Project/S6_Rails_Avanced/J2_Devise_gem/DeviseDemo/DeviseDemo/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#index'
  get '/secret', to: 'pages#secret', as: :secret

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

The_Hacking_Project/S6_Rails_Avanced/J2_Devise_gem/DeviseDemo/DeviseDemo/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :zxcvbnable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable

  def send_devise_notification(notification, *args)
     devise_mailer.send(notification, self, *args).deliver_later
  end
end

The_Hacking_Project/S6_Rails_Avanced/J2_Devise_gem/DeviseDemo/DeviseDemo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # before_action :configure_permitted_parameters, if: :devise_controller?
  #
  # protected
  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.for(:sign_up) << :name
  #   devise_parameter_sanitizer.for(:account_update) << :name
  # end
end

The_Hacking_Project/S6_Rails_Avanced/J2_Devise_gem/DeviseDemo/DeviseDemo/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

The_Hacking_Project/S6_Rails_Avanced/J2_Devise_gem/DeviseDemo/DeviseDemo/app/helpers/application_helper.rb
module ApplicationHelper
  def header(text)
  content_for(:header) { text.to_s }
end
end

The_Hacking_Project/S6_Rails_Avanced/J2_Devise_gem/DeviseDemo/DeviseDemo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseDemo</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <nav class="navbar navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <%= link_to 'Devise Demo', root_path, class: 'navbar-brand' %>
      </div>
      <div id="navbar">
        <ul class="nav navbar-nav">
          <li><%= link_to 'Home', root_path %></li>
        </ul>
        <ul class="nav navbar-nav pull-right">
          <% if !user_signed_in? %>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                render url
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Profile', edit_user_registration_path %></li>
                <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Log In', new_user_session_path %></li>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <body>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
        <%= value %>
        </div>
      <% end %>
    </div>
    <%= yield :top_content %>

    <div class="container">
        <h1><%= yield :header %></h1>
      <%= yield %>
    </div>
  </body>




  <ul class="nav navbar-nav">
  <li><%= link_to 'Home', root_path %></li>
  <% if user_signed_in? %>
    <li><%= link_to 'Secret', secret_path %></li>
  <% end %>
</ul>


</html>